@TodoApi_HostAddress = https://localhost:7188

POST {{TodoApi_HostAddress}}/todoitems
Content-Type: application/json

{
  "name":"walk dog",
  "isComplete":true
}

###

@id=0
PUT {{TodoApi_HostAddress}}/todoitems/2
Content-Type: application/json

{
  "id": 1,
  "name": "Drink vitamins",
  "isComplete": true
}

###

GET {{TodoApi_HostAddress}}/todoitems

###

GET {{TodoApi_HostAddress}}/todoitems/complete

###
